"""adds Book model and configures the database to the __init__.py

Revision ID: 637b60625e65
Revises: 
Create Date: 2021-10-25 17:54:57.994997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '637b60625e65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###
